### ISSUE TITLE
Tag 0.1.0 version

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial/cmake_common_scripts#10]
After we have used this on a few projects and get it working, we should tag a 0.1.0 release so we can start pulling version tags instead of master or commits.

For reference, in progress ports are below. 
1) Noether: https://github.com/ros-industrial/noether/pull/93
2) OPW_Kinematics: https://github.com/Jmeyer1292/opw_kinematics/pull/40

**Comment by traversaro** [comment]
Hi @mpowelson @Levi-Armstrong , thanks a lot for the work on `opw_kinematics`, it is a great package and we are really happy user of it! 
I was looking into packaging `opw_kinematics` in [conda-forge](https://conda-forge.org/), and I noticed that is has now the dependency on this package. Even I guess now it is too late, I wonder if you consider giving it a less-ambiguous name, such as `ros_industrial_cmake_common_scripts` or similar. As you may imagine, `cmake_common_scripts` is quite a common name, that could lead to name collisions with other internal similarly named packages, and in general not be really descriptive for users.

**Comment by mpowelson** [comment]
@Levi-Armstrong I don't feel strongly about this. I may let you and any interested parties at SwRI handle this one.

**Comment by Levi-Armstrong** [comment]
@traversaro Is there a particular package it is conflicting with now? I am not opposed to changing the name but it is already being used by around 10-15 packages some internal so I would like to avoid changing it if possible so I do not have to go through and update all of the packages. That said, if it is currently in conflict with another package on an OS, I will make the change. 

@gavanderhoorn What do you think?

**Comment by traversaro** [comment]
> @traversaro Is there a particular package it is conflicting with now? I am not opposed to changing the name but it is already being used by around 10-15 packages some internal so I would like to avoid changing it if possible so I do not have to go through and update all of the packages.

No, it is not conflicting with anything at the moment. If it is already so used, I understand the rationale for leaving as it is, thanks!

**Comment by traversaro** [comment]
I did not notice this has been fixed, thanks a lot @Levi-Armstrong !
