### ISSUE TITLE
How release on ROS buildfarm but exclude the gtest package?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/cmake_common_scripts#26]
@gavanderhoorn I have started to go through the release process but I am not sure how to exclude the gtest package from the release process. Do you know how to do this? I thought about create a patch which removes it but not sure if that will work.

**Comment by gavanderhoorn** [comment]
I believe you've figured this ([noetic.ignored](https://github.com/ros-industrial-release/cmake_common_scripts-release/blob/96d935394d7cb6a866cbe3100b261e03c83732c3/noetic.ignored)).

**Comment by gavanderhoorn** [comment]
I'm somewhat confused why there is a `gtest` package here, but that's something else.

**Comment by Levi-Armstrong** [comment]
> I believe you've figured this ([noetic.ignored](https://github.com/ros-industrial-release/cmake_common_scripts-release/blob/96d935394d7cb6a866cbe3100b261e03c83732c3/noetic.ignored)).

Yep thank you, once I figured out the right keywords to search for it popped right up. Though it must go in the release repository master branch.

**Comment by gavanderhoorn** [comment]
> Though it must go in the release repository master branch.

yes, indeed.

We do the same thing for `industrial_core` actually: [industrial_core-release/noetic.ignored](https://github.com/ros-industrial-release/industrial_core-release/blob/13e386952bad5f6007998fa8e177ff45963e1f50/noetic.ignored).

**Comment by Levi-Armstrong** [comment]
> I'm somewhat confused why there is a `gtest` package here, but that's something else.

Yea, we moved it here because it is usually the first package in our dependency tree and it also depend on gtest.

**Comment by Levi-Armstrong** [comment]
Though I am not sure it is needed anymore because I think it was added to fix some issues on kinetic builds.

**Comment by Levi-Armstrong** [comment]
> We do the same thing for `industrial_core` actually: [industrial_core-release/noetic.ignored](https://github.com/ros-industrial-release/industrial_core-release/blob/13e386952bad5f6007998fa8e177ff45963e1f50/noetic.ignored).

Another issue I ran into was that now GitHub main branch is called `main` which I had to duplicate and rename master. Do bloom only look for master or is there a way to tell it to know use `main`?

**Comment by gavanderhoorn** [comment]
Good question: I don't know.

Would make for a good ROS Answers question.

I don't see any arg to `bloom-release` to specify this immediately.

Doesn't it just create a `master` branch if there isn't one?

**Comment by Levi-Armstrong** [comment]
> Doesn't it just create a `master` branch if there isn't one?

It did, then I realized that I put the noetic.ignored in the main because it did not skip gtest package. I just copied the file to the master branch and deleted main.

**Comment by Levi-Armstrong** [comment]
One more question. I am going through the release process now for owp_kinematics but it depends on cmake_common_scripts which I when through the process last night. During the process it gave the error below but was not sure if I should skip the generator action or do I have to wait until the rosdistro [PR](https://github.com/ros/rosdistro/pull/27906) for cmake_common_scripts is merged?

``` bash
Pre-verifying Debian dependency keys...
Running 'rosdep update'...
Could not resolve rosdep key 'cmake_common_scripts'
Failed to resolve cmake_common_scripts on ubuntu:focal with: Error running generator: Failed to resolve rosdep key 'cmake_common_scripts', aborting.
cmake_common_scripts is depended on by these packages: ['opw_kinematics']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
<== The following generator action reported that it is missing one or more
    rosdep keys, but that the key exists in other platforms:
'['/usr/bin/git-bloom-generate', '-y', 'rosdebian', '--prefix', 'release/noetic', 'noetic', '-i', '1', '--os-name', 'ubuntu']'

If you are absolutely sure that this key is unavailable for the platform in
question, the generator can be skipped and you can proceed with the release.
Skip generator action and continue with release [y/N]? n
```

**Comment by gavanderhoorn** [comment]
> I was not sure if I should skip the generator action 

No, I don't believe you want to do that.

> do I have to wait until the rosdistro [PR](https://github.com/ros/rosdistro/pull/27906) for cmake_common_scripts is merged?

officially/unfortunately: yes.

Bloom can resolve dependencies from/in the same repository before they are merged into `rosdistro`, but I believe it can't do it for other dependencies.

You *could* trick it by using a custom, local `rosdistro` clone and using that instead of `ros/rosdistro`, but that's probably more effort than it's worth.

**Comment by Levi-Armstrong** [comment]
Thank you for the help. I will wait until it is merged before proceeding.

**Comment by gavanderhoorn** [comment]
> the rosdistro [PR](https://github.com/ros/rosdistro/pull/27906) for cmake_common_scripts is merged?

just looked at your PR: did Bloom not generate a PR for you?

Releases made using Bloom typically contain lots of metadata in the PR description.

If you had to do things manually, I'd add a comment to the PR explaining why. It will probably avoid having to go through a round of comments with the `ros/rosdistro` maintainers.

**Comment by Levi-Armstrong** [comment]
It did not. I kept getting an error when trying to generate the bloom oath token

**Comment by Levi-Armstrong** [comment]
I just manually when through and created the token and updated the file described in this [issue](https://github.com/ros-infrastructure/bloom/issues/448) so I will see if it works the next time around.

**Comment by Levi-Armstrong** [comment]
Error: (Tried multiple time and verified that my username and password was correct.)
``` bash
HTTP Error 404: Not Found (https://api.github.com/authorizations): None

This sometimes fails when the username or password are incorrect, try again?
```

**Comment by gavanderhoorn** [comment]
Not sure. Github has changed some things around tokens and how to acquire them.

Could be Bloom needs to be updated.

Seems you're not the only one:

 - https://github.com/ros-infrastructure/bloom/issues/605
 - https://github.com/ros-infrastructure/bloom/issues/611
 - https://github.com/ros-infrastructure/bloom/issues/590
 - https://github.com/ros-infrastructure/bloom/issues/499
 - etc

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn I have around 10 repositories I need to do a first time release on and wanted to see if there is any reason not to create a single PR against rosdep which adds them all versus individual ones?

**Comment by gavanderhoorn** [comment]
Hm.

I would say a good reason would be traceability.

Separate PRs make it much easier to track what happened where.

It's also easier to review for the `ros/rosdep` reviewers.

Especially if they are unrelated repositories, I would not do everything in a single PR.

**Comment by gavanderhoorn** [comment]
You could consider submitting a single PR, but with multiple commits.

They could then at least be reverted individually.

**Comment by Levi-Armstrong** [comment]
Yea either way is fine with me. It seems like the bottleneck for first time release is getting it merged into rosdep so I was going to create a PR or multiple PR that adds all of the packages I plan to release. This way maybe it will speed things up instead of doing them one at a time and waiting till they get merged.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Thank you for the support!
